spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: crm
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: false
  flyway:
    locations: classpath:db/migration
  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
