spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: ${DB_USERNAME:crm}
    password: ${DB_PASSWORD:crm}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_URI:https://example.com/.well-known/jwks.json}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

app:
  jwt:
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: INFO
