spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: crm
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
